INSERT INTO tasks (name, completion_time_in_seconds, type, xp, description)
VALUES  ('plank', 3000, 'main', 50, 'An exercise training the bodys core.'),
        ('jumping jacks', 3000, 'main', 50, 'An exercise training the heart, lungs, and muscles at the same time'),
        ('squats', 3000, 'main', 50, 'A strength exercise in which the trainee lowers their hips from a standing position and then stands back up.'),
        ('push ups', 3000, 'main', 50, 'A common calisthenics exercise beginning from the prone position, and raising and lowering the body using the arms.'),
        ('stretches', 3000, 'main', 50, 'Stretching keeps the muscles flexible, strong, and healthy, and we need that flexibility to maintain a range of motion in the joints.'),
        ('sit ups', 3000, 'main', 50, 'Sit ups are an excellent core muscle exercise that target your abdominal muscles, hip flexors, and lower back.'),
        ('tree pose', 3000, 'main', 50, 'Stretches the thighs, groins, torso, and shoulders, and builds strength in the ankles and calves, and tones the abdominal muscles.'),
        ('chair pose', 3000, 'main', 50, 'strengthens hip flexors, ankles, calves, and back, and stretches chest and shoulders.'),
        ('drink water', 3000, 'side', 25, 'You should hydrate.'),
        ('stillness', 5000, 'side', 25, 'Stillness is a conscious choice to set aside a period of time and let the body, mind and soul rest.'),
        ('eat', 5000, 'side', 25, 'You should eat.'),
        ('wash dishes', 5000, 'side', 25, 'Clean up after yourself!'),
        ('dips', 5000, 'side', 25, 'Work out the arms, shoulders, back, and core.'),
        ('meal prep', 5000, 'side', 25, 'Meal prep for the week.'),
        ('running in place', 5000, 'side', 25, 'Running in place.'),
        ('stretch neck', 5000, 'side', 25, 'Stretch your neck.');